[package]
name = "atlas_rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.2"
strum = "0.24"
strum_macros = "0.24"
cgmath = "0.18.0"
